language: python
python:
-  3.7.3
install:
  - pip install mkdocs
  - pip install mkdocs-material
script:
  - rm -rf /home/travis/virtualenv/python3.7.3/lib/python3.7/site-packages/material
  - cp -r venv/Lib/site-packages/material /home/travis/virtualenv/python3.7.3/lib/python3.7/site-packages
  - cd blog_code
  - mkdocs build --clean
after_success:  |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    cd blog_code
    cd site
    git init
    git add .
    git -c user.name=$GITHUB_NAME -c user.email=$GITHUB_EMAIL commit -m "Auto Deployment"
    git push -f -q https://$GITHUB_NAME:$GITHUB_API_KEY@github.com/Alikas0/Alikas0.github.io master
    cd "$TRAVIS_BUILD_DIR"
  fi