site_name: 'Latern’station'
site_url: 'https://blog.alikas.cf'
repo_name: 'blog_code'
repo_url: 'https://github.com/Alikas0/blog_code/tree/master/blog_code'

nav:
  - Homepage:
    - 主页: index.md
    - 友情链接: links.md
  - CTF Write-Up:
      - 2018:
          - 2018 RCTF: ctf_write_up/2018/2018rctf.md
      - 2019:
          - 2019 SUCTF: ctf_write_up/2019/2019suctf.md
          - 2019 Aurora内部赛: ctf_write_up/2019/2019aurora.md
          - 2019 RCTF国际赛: ctf_write_up/2019/2019rctf.md
          - 2019 *CTF: ctf_write_up/2019/2019starctf.md
          - 2019 强网杯: ctf_write_up/2019/2019qwb.md
      - Exams:
          - BUUCTF:
              - 简介: ctf_write_up/exams/buuctf/introduction.md
              - MISC: ctf_write_up/exams/buuctf/misc.md
              - Reverse: ctf_write_up/exams/buuctf/reverse.md
          - 旧版Bugku:
              - 简介: ctf_write_up/exams/old_bugku/introduction.md
              - Reverse: ctf_write_up/exams/old_bugku/reverse.md
          - 实验吧:
              - 简介: ctf_write_up/exams/shiyanba/introduction.md
              - Reverse: ctf_write_up/exams/shiyanba/reverse.md
      - SAO: ctf_write_up/sao/reverse_box.md
  - CTF Tools:
      - Z3 : ctf_tools/z3.md
      - Xortool : ctf_tools/xortool.md
      - IDA python: ctf_tools/ida_python.md
  - SZU OJ Solution:
      - 数据结构:
          - 简介: szu_oj/data_structure/introdution.md
          - 顺序表:
              - DS顺序表--类实现: szu_oj/data_structure/1003/1017.md
              - DS顺序表--连续操作: szu_oj/data_structure/1003/1018.md
              - DS顺序表--合并操作: szu_oj/data_structure/1003/1019.md
              - DS顺序表之循环移位: szu_oj/data_structure/1003/1020.md
          - 单链表:
              - DS单链表--类实现: szu_oj/data_structure/1017/1021.md
              - DS单链表--结点交换: szu_oj/data_structure/1017/1022.md
              - DS单链表--合并: szu_oj/data_structure/1017/1023.md
              - DS循环链表—约瑟夫环(Ver. I - A): szu_oj/data_structure/1017/1029.md
          - 链表和栈:
            - DS堆栈--逆序输出（STL栈使用）: szu_oj/data_structure/1029/1031.md
            - DS堆栈--行编辑: szu_oj/data_structure/1029/1033.md
            - DS堆栈--字符替换: szu_oj/data_structure/1029/1036.md
            - DS线性表—多项式相加: szu_oj/data_structure/1029/1024.md
            - DS链表—学生宿舍管理: szu_oj/data_structure/1029/1025.md
            - DS双向链表—祖玛: szu_oj/data_structure/1029/1109.md
          - 栈:
               - DS堆栈--括号匹配: szu_oj/data_structure/1049/1034.md
               - DS栈—排队游戏: szu_oj/data_structure/1049/1040.md
               - DS栈--Web导航: szu_oj/data_structure/1049/1041.md
               - DS堆栈--表达式计算: szu_oj/data_structure/1049/1035.md
               - DS堆栈--迷宫求解: szu_oj/data_structure/1049/1032.md
          - 队列:
              - DS队列之银行排队: szu_oj/data_structure/1062/1037.md
              - DS队列----银行简单模拟: szu_oj/data_structure/1062/1112.md
              - DS队列+堆栈--数制转换: szu_oj/data_structure/1062/1038.md
              - DS队列--组队列: szu_oj/data_structure/1062/1039.md
              - DS队列----银行单队列多窗口模拟: szu_oj/data_structure/1062/1113.md
  - MISC:
    - Ubuntu18.04 64位=>32位程序问题: misc/ubuntu64_32.md
    - Python SimpleHTTPServer: misc/python_http_server.md
    - python脚本: misc/python_script.md
    - 提问的智慧:
        - 简介: misc/how_to_ask_questions_the_smart_way/introduction.md
        - 在提问之前: misc/how_to_ask_questions_the_smart_way/before_you_ask.md
        - 当你在提问时: misc/how_to_ask_questions_the_smart_way/when_you_ask.md
        - 如何解读答案: misc/how_to_ask_questions_the_smart_way/how_to_interpret_answers.md
        - 如何避免扮演失败者: misc/how_to_ask_questions_the_smart_way/on_not_reacting_like_loser.md
        - 不该问的问题: misc/how_to_ask_questions_the_smart_way/questions_not_to_ask.md
        - 好问题与蠢问题: misc/how_to_ask_questions_the_smart_way/good_and_bad_questions.md
        - 如果得不到回答: misc/how_to_ask_questions_the_smart_way/if_you_cant_get_an_answer.md
        - 如何更好地回答问题: misc/how_to_ask_questions_the_smart_way/how_to_answer_questions_in_a_helpful_way.md
        - 完整版: misc/how_to_ask_questions_the_smart_way/how_to_ask_questions_the_smart_way.md
    - Install WSL:
      - 安装: misc/wsl/install.md
      - mklink软链接到非系统盘: misc/wsl/mklink.md
      - 子系统优化: misc/wsl/optimization.md
      - 杂七杂八问题: misc/wsl/questions.md
      - 参考资料: misc/wsl/reference.md
  - Notes:
      - Pwn :
          - 函数 : notes/pwn/function.md
      - 大端序和小端序: notes/big_little_ending.md
      - C++:
         - 笔记: notes/cpp/cpp.md
         - 关键字(保留字): notes/cpp/keywords.md

theme:
  favicon: 'https://raw.githubusercontent.com/Alikas0/files/master/videos/favicon.png'
  language: 'zh'
  logo:
    icon: 'border_color'
  name: 'material'
  palette:
    primary: 'white'
    accent: 'Lime'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/Alikas0'
    - type: 'telegram'
      link: 'https://t.me/Alikas0'

extra_javascript:
  - 'js/extra.js'
  - 'js/gitalk.min.js'
  - 'js/md5.min.js'

extra_css:
  - 'css/gitalk.css'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: true
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: none
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
 # - pymdownx.emoji:
   #   emoji_generator: !!python/name:pymdownx.emoji.to_svg
  #- pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.details