site_name: 'Alikas’station'
site_url: 'https://blog.alikas.cf'
repo_name: 'blog_code'
repo_url: 'https://github.com/Alikas0/blog_code'

nav:
  - Homepage:
    - 主页: index.md
    - 友情链接: links.md
  - CTF Write-Up:
      - 2018:
          - 2018 RCTF: ctf_write_up/2018/2018rctf.md
      - 2019:
          - 2019 Aurora内部赛: ctf_write_up/2019/2019aurora.md
          - 2019 RCTF国际赛: ctf_write_up/2019/2019rctf.md
          - 2019 *CTF: ctf_write_up/2019/2019starctf.md
          - 2019 强网杯: ctf_write_up/2019/2019qwb.md
      - Exams:
          - BUUCTF:
              - 简介: ctf_write_up/exams/buuctf/introduction.md
              - MISC: ctf_write_up/exams/buuctf/misc.md
              - Reverse: ctf_write_up/exams/buuctf/reverse.md
          - 旧版Bugku:
              - 简介: ctf_write_up/exams/old_bugku/introduction.md
              - Reverse: ctf_write_up/exams/old_bugku/reverse.md
          - 实验吧:
              - 简介: ctf_write_up/exams/shiyanba/introduction.md
              - Reverse: ctf_write_up/exams/shiyanba/reverse.md
  - CTF Tools:
      - Xortool : ctf_tools/xortool.md
      - IDA python: ctf_tools/ida_python.md
  - MISC:
    - Python SimpleHTTPServer: misc/python_http_server.md
    - python脚本: misc/python_script.md
    - 提问的智慧:
        - 简介: misc/how_to_ask_questions_the_smart_way/introduction.md
        - 在提问之前: misc/how_to_ask_questions_the_smart_way/before_you_ask.md
        - 当你在提问时: misc/how_to_ask_questions_the_smart_way/when_you_ask.md
        - 如何解读答案: misc/how_to_ask_questions_the_smart_way/how_to_interpret_answers.md
        - 如何避免扮演失败者: misc/how_to_ask_questions_the_smart_way/on_not_reacting_like_loser.md
        - 不该问的问题: misc/how_to_ask_questions_the_smart_way/questions_not_to_ask.md
        - 好问题与蠢问题: misc/how_to_ask_questions_the_smart_way/good_and_bad_questions.md
        - 如果得不到回答: misc/how_to_ask_questions_the_smart_way/if_you_cant_get_an_answer.md
        - 如何更好地回答问题: misc/how_to_ask_questions_the_smart_way/how_to_answer_questions_in_a_helpful_way.md
        - 完整版: misc/how_to_ask_questions_the_smart_way/how_to_ask_questions_the_smart_way.md
    - Install WSL:
      - 安装: misc/wsl/install.md
      - mklink软链接到非系统盘: misc/wsl/mklink.md
      - 子系统优化: misc/wsl/optimization.md
      - 杂七杂八问题: misc/wsl/questions.md
      - 参考资料: misc/wsl/reference.md
  - Notes:
      - 大端序和小端序: notes/big_little_ending.md
      - C++:
         - 笔记: notes/cpp/cpp.md
         - 关键字(保留字): notes/cpp/keywords.md

theme:
  favicon: 'https://raw.githubusercontent.com/Alikas0/files/master/videos/favicon.png'
  language: 'zh'
  logo:
    icon: 'border_color'
  name: 'material'
  palette:
    primary: 'white'
    accent: 'Lime'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/Alikas0'
    - type: 'telegram'
      link: 'https://t.me/Alikas0'

extra_javascript:
  - 'js/extra.js'
  - 'js/gitalk.min.js'
  - 'js/md5.min.js'


extra_css:
  - 'css/gitalk.css'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: true
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: none
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
 # - pymdownx.emoji:
   #   emoji_generator: !!python/name:pymdownx.emoji.to_svg
  #- pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.details